name: Feature request
description: An idea for Ancilo
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Which problem would it solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
