// Generates src/api/schema.d.ts from the daemon's OpenAPI document.
// The document comes from the e2e harness (a real daemon with fakes).
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const root = new URL("../..", import.meta.url).pathname;
execFileSync("cargo", ["build", "-q", "-p", "ancilo-e2e", "-p", "ancilo", "-p", "ancilo-testkit", "--bins"], { cwd: root, stdio: "inherit" });
const doc = execFileSync(`${root}target/debug/ancilo-e2e`, ["--openapi"], { input: "", maxBuffer: 64 << 20 }).toString();
writeFileSync(new URL("../src/api/openapi.json", import.meta.url), doc);
const ast = await openapiTS(JSON.parse(doc));
writeFileSync(
  new URL("../src/api/schema.d.ts", import.meta.url),
  "// Generated by `npm run gen:api` from the daemon's OpenAPI document – do not edit.\n" + astToString(ast),
);
console.log("src/api/schema.d.ts updated");
